version: "3.8"

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: mwaza3adb
      POSTGRES_USER: mwaza3auser
      POSTGRES_PASSWORD: user
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"

  authentication-service:
    build: ./authentication-service
    expose:
      - "8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mwaza3adb
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      - postgres
      - discovery-server

  user-service:
    build: ./user-service
    expose:
      - "8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mwaza3adb
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      - postgres
      - discovery-server

  course-service:
    build: ./course-service
    expose:
      - "8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mwaza3adb
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      - postgres
      - discovery-server

  subscription-service:
    build: ./subscription-service
    expose:
      - "8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mwaza3adb
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      - postgres
      - discovery-server

  assessment-service:
    build: ./assessment-service
    expose:
      - "8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mwaza3adb
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      - postgres
      - discovery-server

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
      - authentication-service
      - user-service
      - course-service
      - subscription-service
      - assessment-service

volumes:
  postgres_data:
